spring:
  application:
    name: Auth-Service-App
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml

app:
  jwt:
    secret: hVxq8VbQ9p5F2l5rX3n8Xk1QvL8fK0uD5t3jH4yM7n9rB2mD8vL1jX5qT0uC9k6y
    expiration: 3600000     # 1 hour in ms
    refreshExpiration: 1209600000 # 14 days

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: app.log
